language: ruby
cache: bundler
branches:
 only:
  - release
script:
 - JEKYLL_ENV=production bundle exec jekyll build --destination public
deploy:
 provider: pages
 local-dir: ./public
 target-branch: master
 email: deploy@travis-ci.org
 name: Deployment Bot
 skip-cleanup: true
 github-token: $GITHUB_TOKEN
 keep-history: true
 on:
  branch: release