---
title: Lee Sheppard
timezone: Australia/Sydney
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: lee@leesheppard.com
description: "I'm a Sydney based writer, cartoonist and code monkey. I've won various
  awards in many industries. Member of SCBWI Australia/NZ."
repository: "leesheppard/leesheppard.github.io"
baseurl: "" # this must be an empty string
url: http://leesheppard.github.io

twitter_username: leesheppard
github_username: leesheppard
dribbble_username: leesheppard
instagram_username: leesheppard
linkedin_username: leesheppard

author:
  name: "Lee Sheppard"
  bio: "I'm a Sydney based writer, cartoonist and code monkey. Member of SCBWI Australia/NZ."

cloudinary:
  cloud_name: leesheppard
  verbose: true
  origin_url: https://lee.sheppard.io

# Build settings
github: [metadata]
markdown: kramdown
plugins_dir: ./_plugins
jekyll_get:
  - data: github
    json: 'https://api.github.com/users/leesheppard/repos'
    cache: false
plugins:
  - jekyll-watch
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postcss
  - jekyll-purgecss
  - jekyll-cloudinary

exclude:
  - ['.circleci', 'spec', '.travis.yml', '.idea', '.now']
  - "*.config.js"
  - "package*.json"
  - "node_modules"
destination: public
source: src
css_dir: css
