# Site settings
title: Lee Sheppard
email: lee@leesheppard.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a Sydney based writer, cartoonist and code monkey. I've won various awards
  in many industries. Member of SCBWI Australia/NZ.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://leesheppard.github.io" # the base hostname & protocol for your site
twitter_username: leesheppard
github_username:  leesheppard
timezone: Australia/Sydney

# Build settings
markdown: kramdown
