---
title: Lee Sheppard
timezone: Australia/Sydney
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: lee@leesheppard.com
description: 'I''m a Sydney based writer, cartoonist and code monkey. I''ve won various
  awards in many industries. Member of SCBWI Australia/NZ.

'
baseurl: 
url: http://leesheppard.github.io
twitter_username: leesheppard
github_username: leesheppard
markdown: kramdown
gems:
- jekyll-watch
- jekyll-assets
- jekyll-admin
